model_params:
  name: 'SimQRVAE'
  latent_dim: 2
  hidden_dim: 50

data_params:
  data_path: "data/simple_sim/"
  train_batch_size: 500
  val_batch_size:  500
  num_workers: 0


exp_params:
  name: "without_conditioning"
  LR: 0.001
  weight_decay: 0.0
  # scheduler_gamma: 0.95 # NOTE: Uncomment this line to use a scheduler
  kld_weight: 0.28
  manual_seed: 42

trainer_params:
  devices: [0]
  log_every_n_steps: 1
  max_epochs: 500

logging_params:
  save_dir: "logs/"
  name: "SimQRVAE"
  